import tkinter as tk
def userloginpanel():
    userloginpanel=tk.Tk()
    userloginpanel.state("zoomed")
    userloginpanel.config(bg="black")
    userloginpanel.title("userloginpanel")
    userloginwelcomemainscreen=tk.Label(userloginpanel,text="User Login Panel",font="Verdana 64", bg="black", fg="red")
    userloginwelcomemainscreen.place(x=320,y=100)
    usertext=tk.Label(userloginpanel,text="User Name : ",font="Verdana 15", bg="red", fg="white")
    usertext.place(x=200,y=300)
    userinput=tk.Entry(userloginpanel,bg="gray", fg="black", font="verdana 17 bold")
    userinput.place(x=380, y=300, width=900, height=30)
    textpassword=tk.Label(userloginpanel,text="Password : ",font="Verdana 15", bg="red", fg="white")
    textpassword.place(x=200,y=450,width=150)
    passwordinput=tk.Entry(userloginpanel,bg="gray", fg="black",font="verdana 17 bold")
    passwordinput.place(x=380, y=450, width=900, height=30)
    def loginuser():
        # We have defined a list to hold user information.
        userinformation=list()
        username=userinput.get()
        userinformation.append(username)
        password=passwordinput.get()
        userinformation.append(password)
        print(userinformation)
        if username in userinformation and password in userinformation:
            # This is our parent class that inherited the car and motor class...
            
            class user():
                def __init__(self,car1,car2,car3):
                    self.__car1=car1
                    self.__car2=car2
                    self.__car3=car3
                
                
            # This class is a child class that inherits from our user class...
            class car(user):
                def __init__(self, car1, car2, car3):
                    super().__init__(car1, car2, car3)
                def caroptions(self):
                    caroptions=tk.Tk()
                    caroptions.title("Car Options")
                    caroptions.config(bg="gray")
                    caroptions.state("zoomed")
                    welcometextuserscreen=tk.Label(caroptions,text="Car Options",font="Verdana 32", bg="red", fg="white")
                    welcometextuserscreen.place(x=580,y=100)
                    def choicebmvattribute():
                        bmvfeatureselectscreen=tk.Tk()
                        bmvfeatureselectscreen.state("zoomed")
                        bmvfeatureselectscreen.config(bg="gray")
                        bmvfeatureselectscreen.title("Bmv Feature Select Screen")
                        textbmvfeature=tk.Label(bmvfeatureselectscreen,text="Bmv Feature Select Screen",font="Verdana 32", bg="red", fg="white")
                        textbmvfeature.place(x=475,y=100)
                        textmodel=tk.Label(bmvfeatureselectscreen,text="Model : ",font="Verdana 16", bg="red", fg="white")
                        textmodel.place(x=300,y=300)
                        colouroftext=tk.Label(bmvfeatureselectscreen,text="Colour : ",font="Verdana 16", bg="red", fg="white")
                        colouroftext.place(x=300,y=450)
                        priceoftext=tk.Label(bmvfeatureselectscreen,text="Price : ",font="Verdana 16", bg="red", fg="white")
                        priceoftext.place(x=300,y=600)
                        model1=tk.Checkbutton(bmvfeatureselectscreen,text="320",bg="gray",fg="red")
                        model1.place(x=450,y=305)
                        model2=tk.Checkbutton(bmvfeatureselectscreen,text="520",bg="gray",fg="red")
                        model2.place(x=600,y=305,width=30)
                        model3=tk.Checkbutton(bmvfeatureselectscreen,text="820",bg="gray",fg="red")
                        model3.place(x=750,y=305)
                        firstcolor=tk.Checkbutton(bmvfeatureselectscreen,text="Red",bg="gray",fg="red")
                        firstcolor.place(x=450,y=455)
                        secondcolor=tk.Checkbutton(bmvfeatureselectscreen,text="White",bg="gray",fg="red")
                        secondcolor.place(x=600,y=455)
                        thirdcolor=tk.Checkbutton(bmvfeatureselectscreen,text="Black",bg="gray",fg="red")
                        thirdcolor.place(x=750,y=455)
                        firstprice=tk.Checkbutton(bmvfeatureselectscreen,text="1000 TL",bg="gray",fg="red")
                        firstprice.place(x=450,y=605)
                        secondprice=tk.Checkbutton(bmvfeatureselectscreen,text="2000 TL",bg="gray",fg="red")
                        secondprice.place(x=600,y=605)
                        thirdprice=tk.Checkbutton(bmvfeatureselectscreen,text="3000 TL",bg="gray",fg="red")
                        thirdprice.place(x=750,y=605)
                        def paymentbmv():
                            bmvpaymentscreen=tk.Tk()
                            bmvpaymentscreen.state("zoomed")
                            bmvpaymentscreen.config(bg="gray")
                            bmvpaymentscreen.title("Bmv Payment Screen")
                            welcome_label=tk.Label(bmvpaymentscreen,text="Welcome to Payment Panel",font="Verdana 32", bg="red", fg="white")
                            welcome_label.place(x=400,y=100)
                            cardnumbertext=tk.Label(bmvpaymentscreen,text="Card No : ",font="Verdana 15", bg="red", fg="white",width=17)
                            cardnumbertext.place(x=230,y=300)
                            cvvtext=tk.Label(bmvpaymentscreen,text="Son Kullanma Tarihi : ",font="Verdana 15", bg="red", fg="white")
                            cvvtext.place(x=230,y=400)
                            cvv=tk.Label(bmvpaymentscreen,text="CVV : ",font="Verdana 15", bg="red", fg="white",width=17)
                            cvv.place(x=230,y=500)
                            cardnoinput=tk.Entry(bmvpaymentscreen,bg="white", fg="black", font="verdana 17 bold")
                            cardnoinput.place(x=470, y=300, width=900, height=30)
                            cvvinput=tk.Entry(bmvpaymentscreen,bg="white", fg="black", font="verdana 17 bold")
                            cvvinput.place(x=470, y=400, width=900, height=30)
                            cvvinput=tk.Entry(bmvpaymentscreen,bg="white", fg="black", font="verdana 17 bold")
                            cvvinput.place(x=470, y=500, width=900, height=30)
                            def paymentcompletedtext():
                                paymentcompletedtext=tk.Label(bmvpaymentscreen,text="YOUR OPEARTİON COMPLETED WİTH SUCCESS",font="Verdana 15", bg="red", fg="white",width=95,height=2)
                                paymentcompletedtext.place(x=200,y=565)
                            bmvpaymentcompletedbutton=tk.Button(bmvpaymentscreen,text="Ödemeyi tamamla",fg="red",bg="black",font="verdana 32",command=paymentcompletedtext)
                            bmvpaymentcompletedbutton.place(x=600,y=650)
                            bmvpaymentscreen.mainloop()
                        bmvpayment=tk.Button(bmvfeatureselectscreen,text="Do Payment",fg="red",bg="black",font="verdana 32",command=paymentbmv)
                        bmvpayment.place(x=970,y=420)
                    self.__car1=tk.Button(caroptions,text="BMV",fg="white",bg="black",font="verdana 32",command=choicebmvattribute)
                    self.__car1.place(x=400,y=300,width=800)
                    def choiceattributeaudi():
                        audiattributechoicescreen=tk.Tk()
                        audiattributechoicescreen.state("zoomed")
                        audiattributechoicescreen.config(bg="gray")
                        audiattributechoicescreen.title("Audi Attribute Choice Screen")
                        textaudiattribute=tk.Label(audiattributechoicescreen,text="Audi Attribute Choice Screen",font="Verdana 32", bg="red", fg="white")
                        textaudiattribute.place(x=475,y=100)
                        textmodel=tk.Label(audiattributechoicescreen,text="Model : ",font="Verdana 16", bg="red", fg="white")
                        textmodel.place(x=300,y=300)
                        textcolor=tk.Label(audiattributechoicescreen,text="Color : ",font="Verdana 16", bg="red", fg="white")
                        textcolor.place(x=300,y=450)
                        textprice=tk.Label(audiattributechoicescreen,text="Price : ",font="Verdana 16", bg="red", fg="white")
                        textprice.place(x=300,y=600)
                        model1=tk.Checkbutton(audiattributechoicescreen,text="A3",bg="gray",fg="red")
                        model1.place(x=450,y=305)
                        model2=tk.Checkbutton(audiattributechoicescreen,text="A5",bg="gray",fg="red")
                        model2.place(x=600,y=305,width=30)
                        model3=tk.Checkbutton(audiattributechoicescreen,text="A6",bg="gray",fg="red")
                        model3.place(x=750,y=305)
                        color1=tk.Checkbutton(audiattributechoicescreen,text="Red",bg="gray",fg="red")
                        color1.place(x=450,y=455)
                        color2=tk.Checkbutton(audiattributechoicescreen,text="White",bg="gray",fg="red")
                        color2.place(x=600,y=455)
                        color3=tk.Checkbutton(audiattributechoicescreen,text="Black",bg="gray",fg="red")
                        color3.place(x=750,y=455)
                        price1=tk.Checkbutton(audiattributechoicescreen,text="1000 $",bg="gray",fg="red")
                        price1.place(x=450,y=605)
                        price2=tk.Checkbutton(audiattributechoicescreen,text="2000 $",bg="gray",fg="red")
                        price2.place(x=600,y=605)
                        price3=tk.Checkbutton(audiattributechoicescreen,text="3000 $",bg="gray",fg="red")
                        price3.place(x=750,y=605)
                        audipaymentcompletedbutton=tk.Button(audiattributechoicescreen,text="Do Payment",fg="red",bg="black",font="verdana 32",command=audipaymentscreen)
                        audipaymentcompletedbutton.place(x=1000,y=440)
                    def audipaymentscreen():
                                    audipaymentscreen=tk.Tk()
                                    audipaymentscreen.state("zoomed")
                                    audipaymentscreen.config(bg="gray")
                                    audipaymentscreen.title("Audi Payment Screen")
                                    welcome_label=tk.Label(audipaymentscreen,text="Welcome to Payment Panel!",font="Verdana 32", bg="red", fg="white")
                                    welcome_label.place(x=400,y=100)
                                    textcardno=tk.Label(audipaymentscreen,text="Card No : ",font="Verdana 15", bg="red", fg="white",width=17)
                                    textcardno.place(x=230,y=300)
                                    usedatelasttext=tk.Label(audipaymentscreen,text="Use For Last Date  : ",font="Verdana 15", bg="red", fg="white")
                                    usedatelasttext.place(x=230,y=400)
                                    textcvv=tk.Label(audipaymentscreen,text="CVV : ",font="Verdana 15", bg="red", fg="white",width=17)
                                    textcvv.place(x=230,y=500)
                                    inputcardno=tk.Entry(audipaymentscreen,bg="white", fg="black", font="verdana 17 bold")
                                    inputcardno.place(x=470, y=300, width=900, height=30)
                                    inputlastdateused=tk.Entry(audipaymentscreen,bg="white", fg="black", font="verdana 17 bold")
                                    inputlastdateused.place(x=470, y=400, width=900, height=30)
                                    cvvinput=tk.Entry(audipaymentscreen,bg="white", fg="black", font="verdana 17 bold")
                                    cvvinput.place(x=470, y=500, width=900, height=30)    
                                    
                                    def paymentauditext():
                                        textpaymentcompleted=tk.Label(audipaymentscreen,text="Payment Completed",font="Verdana 15", bg="red", fg="white",width=95,height=2)
                                        textpaymentcompleted.place(x=200,y=565)
                                    audipayment=tk.Button(audipaymentscreen,text="Ödemeyi Tamamla",fg="red",bg="black",font="verdana 32",command=paymentauditext)
                                    audipayment.place(x=600,y=650)

                    self.__car2=tk.Button(caroptions,text="Audi",fg="white",bg="black",font="verdana 32",command=choiceattributeaudi)
                    self.__car2.place(x=400,y=450,width=800)
                    def mersedesattributechoice():
                        mersedesattributechoicescreen=tk.Tk()
                        mersedesattributechoicescreen.state("zoomed")
                        mersedesattributechoicescreen.config(bg="gray")
                        mersedesattributechoicescreen.title("Mersedes Attribute Choice Screen")
                        textmercedesattribute=tk.Label(mersedesattributechoicescreen,text="Mersedes Attribute Choice Screen",font="Verdana 32", bg="red", fg="white")
                        textmercedesattribute.place(x=475,y=100)
                        textmodel=tk.Label(mersedesattributechoicescreen,text="Model : ",font="Verdana 16", bg="red", fg="white")
                        textmodel.place(x=300,y=300)
                        textcolor=tk.Label(mersedesattributechoicescreen,text="Color : ",font="Verdana 16", bg="red", fg="white")
                        textcolor.place(x=300,y=450)
                        textprice=tk.Label(mersedesattributechoicescreen,text="Price : ",font="Verdana 16", bg="red", fg="white")
                        textprice.place(x=300,y=600)
                        model1=tk.Checkbutton(mersedesattributechoicescreen,text="C180",bg="gray",fg="red")
                        model1.place(x=450,y=305)
                        model2=tk.Checkbutton(mersedesattributechoicescreen,text="A200",bg="gray",fg="red")
                        model2.place(x=600,y=305,width=30)
                        model3=tk.Checkbutton(mersedesattributechoicescreen,text="G63",bg="gray",fg="red")
                        model3.place(x=750,y=305)
                        color1=tk.Checkbutton(mersedesattributechoicescreen,text="Red",bg="gray",fg="red")
                        color1.place(x=450,y=455)
                        color2=tk.Checkbutton(mersedesattributechoicescreen,text="White",bg="gray",fg="red")
                        color2.place(x=600,y=455)
                        color3=tk.Checkbutton(mersedesattributechoicescreen,text="Black",bg="gray",fg="red")
                        color3.place(x=750,y=455)
                        price1=tk.Checkbutton(mersedesattributechoicescreen,text="1000 $",bg="gray",fg="red")
                        price1.place(x=450,y=605)
                        price2=tk.Checkbutton(mersedesattributechoicescreen,text="2000 $",bg="gray",fg="red")
                        price2.place(x=600,y=605)
                        price3=tk.Checkbutton(mersedesattributechoicescreen,text="3000 $",bg="gray",fg="red")
                        price3.place(x=750,y=605)
                        def mersedespaymentscreen():
                            mersedespaymentscreen=tk.Tk()
                            mersedespaymentscreen.state("zoomed")
                            mersedespaymentscreen.config(bg="gray")
                            mersedespaymentscreen.title("Mersedes Payment Screen")
                            welcome_label=tk.Label(mersedespaymentscreen,text="Welcome to Payment Panel",font="Verdana 32", bg="red", fg="white")
                            welcome_label.place(x=400,y=100)
                            textcardno=tk.Label(mersedespaymentscreen,text="Card No : ",font="Verdana 15", bg="red", fg="white",width=17)
                            textcardno.place(x=230,y=300)
                            textexprirationdate=tk.Label(mersedespaymentscreen,text="Expiration Date : ",font="Verdana 15", bg="red", fg="white")
                            textexprirationdate.place(x=230,y=400)
                            textcvv=tk.Label(mersedespaymentscreen,text="CVV : ",font="Verdana 15", bg="red", fg="white",width=17)
                            textcvv.place(x=230,y=500)
                            cardnoinput=tk.Entry(mersedespaymentscreen,bg="white", fg="black", font="verdana 17 bold")
                            cardnoinput.place(x=470, y=300, width=900, height=30)
                            expirationdateinput=tk.Entry(mersedespaymentscreen,bg="white", fg="black", font="verdana 17 bold")
                            expirationdateinput.place(x=470, y=400, width=900, height=30)
                            cvvinput=tk.Entry(mersedespaymentscreen,bg="white", fg="black", font="verdana 17 bold")
                            cvvinput.place(x=470, y=500, width=900, height=30)
                            def paymentauditext():
                                textpaymentcompleted=tk.Label(mersedespaymentscreen,text="PAYMENT COMLETED!",font="Verdana 15", bg="red", fg="white",width=95,height=2)
                                textpaymentcompleted.place(x=200,y=565)
                            mersedespayment=tk.Button(mersedespaymentscreen,text="Comlete Payment",fg="red",bg="black",font="verdana 32",command=paymentauditext)
                            mersedespayment.place(x=600,y=650)

                        mersedescompletepaymentbutton=tk.Button(mersedesattributechoicescreen,text="Do Payment",fg="red",bg="black",font="verdana 32",command=mersedespaymentscreen)
                        mersedescompletepaymentbutton.place(x=1000,y=440)
                        mersedesattributechoicescreen.mainloop()
                    self.__arac3=tk.Button(caroptions,text="Mercedes",fg="white",bg="black",font="verdana 32",command=mersedesattributechoice)
                    self.__arac3.place(x=400,y=600,width=800)
                    caroptions.mainloop()
            car=car("","","")
            # This class is a child class that inherits from our user class...
            class motor(user):
                def __init__(self, car1, car2, car3):
                    super().__init__(car1, car2, car3)
                def motor_options(self):
                    motoroptionsscreen=tk.Tk()
                    motoroptionsscreen.title("Motor Options")
                    motoroptionsscreen.config(bg="gray")
                    motoroptionsscreen.state("zoomed")
                    welcometextuserscreen=tk.Label(motoroptionsscreen,text="Motor Options",font="Verdana 32", bg="red", fg="white")
                    welcometextuserscreen.place(x=530,y=100)
                    def bmvmotorattributechoicescreen():
                        bmvmotorattributechoicescreen=tk.Tk()
                        bmvmotorattributechoicescreen.title("Bmv Motor Screen for Choice Attributes")
                        bmvmotorattributechoicescreen.config(bg="gray")
                        bmvmotorattributechoicescreen.state("zoomed")
                        textbmvattribute=tk.Label(bmvmotorattributechoicescreen,text="Bmv Motor Screen for Choice Attributes",font="Verdana 32", bg="red", fg="white")
                        textbmvattribute.place(x=475,y=100)
                        textmodel=tk.Label(bmvmotorattributechoicescreen,text="Model : ",font="Verdana 16", bg="red", fg="white")
                        textmodel.place(x=300,y=300)
                        textcolor=tk.Label(bmvmotorattributechoicescreen,text="Color : ",font="Verdana 16", bg="red", fg="white")
                        textcolor.place(x=300,y=450)
                        textprice=tk.Label(bmvmotorattributechoicescreen,text="Price : ",font="Verdana 16", bg="red", fg="white")
                        textprice.place(x=300,y=600)
                        model1=tk.Checkbutton(bmvmotorattributechoicescreen,text="R 1250 GS",bg="gray",fg="red")
                        model1.place(x=450,y=305)
                        model2=tk.Checkbutton(bmvmotorattributechoicescreen,text="S 1000 XR",bg="gray",fg="red")
                        model2.place(x=600,y=305)
                        model3=tk.Checkbutton(bmvmotorattributechoicescreen,text="F 900 XR",bg="gray",fg="red")
                        model3.place(x=750,y=305)
                        color1=tk.Checkbutton(bmvmotorattributechoicescreen,text="Red",bg="gray",fg="red")
                        color1.place(x=450,y=455)
                        color2=tk.Checkbutton(bmvmotorattributechoicescreen,text="White",bg="gray",fg="red")
                        color2.place(x=600,y=455)
                        color3=tk.Checkbutton(bmvmotorattributechoicescreen,text="Black",bg="gray",fg="red")
                        color3.place(x=750,y=455)
                        price1=tk.Checkbutton(bmvmotorattributechoicescreen,text="1000$",bg="gray",fg="red")
                        price1.place(x=450,y=605)
                        price2=tk.Checkbutton(bmvmotorattributechoicescreen,text="2000$",bg="gray",fg="red")
                        price2.place(x=600,y=605)
                        price3=tk.Checkbutton(bmvmotorattributechoicescreen,text="3000$",bg="gray",fg="red")
                        price3.place(x=750,y=605)
                        def bmvmotorpayment():
                            bmvmotorpaymentscreen=tk.Tk()
                            bmvmotorpaymentscreen.state("zoomed")
                            bmvmotorpaymentscreen.config(bg="gray")
                            bmvmotorpaymentscreen.title("Bmv Motor Payment Screen")
                            welcome_label=tk.Label(bmvmotorpaymentscreen,text="Welcome to Payment Panel!",font="Verdana 32", bg="red", fg="white")
                            welcome_label.place(x=400,y=100)
                            textcardno=tk.Label(bmvmotorpaymentscreen,text="Card No : ",font="Verdana 15", bg="red", fg="white",width=17)
                            textcardno.place(x=230,y=300)
                            textinspirationdate=tk.Label(bmvmotorpaymentscreen,text="Inspiration Date : ",font="Verdana 15", bg="red", fg="white")
                            textinspirationdate.place(x=230,y=400)
                            textcvv=tk.Label(bmvmotorpaymentscreen,text="CVV : ",font="Verdana 15", bg="red", fg="white",width=17)
                            textcvv.place(x=230,y=500)
                            cardnoinput=tk.Entry(bmvmotorpaymentscreen,bg="white", fg="black", font="verdana 17 bold")
                            cardnoinput.place(x=470, y=300, width=900, height=30)
                            inpirationdateinput=tk.Entry(bmvmotorpaymentscreen,bg="white", fg="black", font="verdana 17 bold")
                            inpirationdateinput.place(x=470, y=400, width=900, height=30)
                            cvvinput=tk.Entry(bmvmotorpaymentscreen,bg="white", fg="black", font="verdana 17 bold")
                            cvvinput.place(x=470, y=500, width=900, height=30)
                            def bmwmotorpaymenttext():
                                bmwmotorpaymentcomletedtext=tk.Label(bmvmotorpaymentscreen,text="PAYMENT COMLETED!",font="Verdana 15", bg="red", fg="white",width=95,height=2)
                                bmwmotorpaymentcomletedtext.place(x=200,y=565)
                            bmvmotorpayment=tk.Button(bmvmotorpaymentscreen,text="Complete Payment!",fg="red",bg="black",font="verdana 32",command=bmwmotorpaymenttext)
                            bmvmotorpayment.place(x=600,y=650)
                        bmvmotorpaymentcompletedbutton=tk.Button(bmvmotorattributechoicescreen,text="Complete Payment!",fg="red",bg="black",font="verdana 32",command=bmvmotorpayment)
                        bmvmotorpaymentcompletedbutton.place(x=1000,y=440)  
                    self.__car1=tk.Button(motoroptionsscreen,text="BMV",fg="white",bg="black",font="verdana 32",command=bmvmotorattributechoicescreen)
                    self.__car1.place(x=400,y=300,width=800)
                    def hondamotorattributechoiceoperation():
                        hondamotorscreenforchoiceattributes=tk.Tk()
                        hondamotorscreenforchoiceattributes.title("Honda Choice Screen for Motor Options")
                        hondamotorscreenforchoiceattributes.config(bg="gray")
                        hondamotorscreenforchoiceattributes.state("zoomed")
                        texthondamotorattribute=tk.Label(hondamotorscreenforchoiceattributes,text="Honda Özellik Seçme Ekranı",font="Verdana 32", bg="red", fg="white")
                        texthondamotorattribute.place(x=475,y=100)
                        textmodel=tk.Label(hondamotorscreenforchoiceattributes,text="Model : ",font="Verdana 16", bg="red", fg="white")
                        textmodel.place(x=300,y=300)
                        textcolor=tk.Label(hondamotorscreenforchoiceattributes,text="Color : ",font="Verdana 16", bg="red", fg="white")
                        textcolor.place(x=300,y=450)
                        textprice=tk.Label(hondamotorscreenforchoiceattributes,text="Price : ",font="Verdana 16", bg="red", fg="white")
                        textprice.place(x=300,y=600)
                        model1=tk.Checkbutton(hondamotorscreenforchoiceattributes,text="Activa S",bg="gray",fg="red")
                        model1.place(x=450,y=305)
                        model2=tk.Checkbutton(hondamotorscreenforchoiceattributes,text="PCX 125",bg="gray",fg="red")
                        model2.place(x=600,y=305)
                        model3=tk.Checkbutton(hondamotorscreenforchoiceattributes,text="Spacy Alpha",bg="gray",fg="red")
                        model3.place(x=750,y=305)
                        color1=tk.Checkbutton(hondamotorscreenforchoiceattributes,text="Red",bg="gray",fg="red")
                        color1.place(x=450,y=455)
                        color2=tk.Checkbutton(hondamotorscreenforchoiceattributes,text="White",bg="gray",fg="red")
                        color2.place(x=600,y=455)
                        color3=tk.Checkbutton(hondamotorscreenforchoiceattributes,text="Black",bg="gray",fg="red")
                        color3.place(x=750,y=455)
                        price1=tk.Checkbutton(hondamotorscreenforchoiceattributes,text="1000 $",bg="gray",fg="red")
                        price1.place(x=450,y=605)
                        price2=tk.Checkbutton(hondamotorscreenforchoiceattributes,text="2000 $",bg="gray",fg="red")
                        price2.place(x=600,y=605)
                        price3=tk.Checkbutton(hondamotorscreenforchoiceattributes,text="3000 $",bg="gray",fg="red")
                        price3.place(x=750,y=605)
                        def hondamotorpayment():
                            hondamotorpaymentscreen=tk.Tk()
                            hondamotorpaymentscreen.state("zoomed")
                            hondamotorpaymentscreen.config(bg="gray")
                            hondamotorpaymentscreen.title("Honda Motor Payment Screen")
                            welcome_label=tk.Label(hondamotorpaymentscreen,text="Welcome to Payment Panel",font="Verdana 32", bg="red", fg="white")
                            welcome_label.place(x=400,y=100)
                            textcardno=tk.Label(hondamotorpaymentscreen,text="Card No : ",font="Verdana 15", bg="red", fg="white",width=17)
                            textcardno.place(x=230,y=300)
                            textexpirationdate=tk.Label(hondamotorpaymentscreen,text="Expression Date : ",font="Verdana 15", bg="red", fg="white")
                            textexpirationdate.place(x=230,y=400)
                            textcvv=tk.Label(hondamotorpaymentscreen,text="CVV : ",font="Verdana 15", bg="red", fg="white",width=17)
                            textcvv.place(x=230,y=500)
                            cardnoinput=tk.Entry(hondamotorpaymentscreen,bg="white", fg="black", font="verdana 17 bold")
                            cardnoinput.place(x=470, y=300, width=900, height=30)
                            expirationdateinput=tk.Entry(hondamotorpaymentscreen,bg="white", fg="black", font="verdana 17 bold")
                            expirationdateinput.place(x=470, y=400, width=900, height=30)
                            cvvinput=tk.Entry(hondamotorpaymentscreen,bg="white", fg="black", font="verdana 17 bold")
                            cvvinput.place(x=470, y=500, width=900, height=30)
                            def paymenthondamotortext():
                                yazihondamotorodemetamamlandı=tk.Label(hondamotorpaymentscreen,text="ISLEMİNİZ BAŞARIYLA GERÇEKLEŞMİŞTİR.",font="Verdana 15", bg="red", fg="white",width=95,height=2)
                                yazihondamotorodemetamamlandı.place(x=200,y=565)
                            hondamotorodeme=tk.Button(hondamotorpaymentscreen,text="Ödemeyi Tamamla",fg="red",bg="black",font="verdana 32",command=paymenthondamotortext)
                            hondamotorodeme.place(x=600,y=650)
                        hondamotorodemetamamlabuton=tk.Button(hondamotorscreenforchoiceattributes,text="Ödeme Yap",fg="red",bg="black",font="verdana 32",command=hondamotorpayment)
                        hondamotorodemetamamlabuton.place(x=1000,y=440)
                        hondamotorattributechoiceoperation.mainloop()
                    self.__arac2=tk.Button(motoroptionsscreen,text="Honda",fg="white",bg="black",font="verdana 32",command=hondamotorattributechoiceoperation)
                    self.__arac2.place(x=400,y=450,width=800)
                    def cavazakiozelliksecmeekranı():
                        cavazakimotorozelliksecmeekranı=tk.Tk()
                        cavazakimotorozelliksecmeekranı.title("Cavazaki Motor Özellikleri Seçme Ekranı")
                        cavazakimotorozelliksecmeekranı.config(bg="gray")
                        cavazakimotorozelliksecmeekranı.state("zoomed")
                        yazicavazakimotorozellik=tk.Label(cavazakimotorozelliksecmeekranı,text="Honda Özellik Seçme Ekranı",font="Verdana 32", bg="red", fg="white")
                        yazicavazakimotorozellik.place(x=475,y=100)
                        yazimodel=tk.Label(cavazakimotorozelliksecmeekranı,text="Model : ",font="Verdana 16", bg="red", fg="white")
                        yazimodel.place(x=300,y=300)
                        yazirenk=tk.Label(cavazakimotorozelliksecmeekranı,text="Renk : ",font="Verdana 16", bg="red",fg="white")
                        yazirenk.place(x=300,y=450)
                        yazifiyat=tk.Label(cavazakimotorozelliksecmeekranı,text="Fiyat : ",font="Verdana 16", bg="red", fg="white")
                        yazifiyat.place(x=300,y=600)
                        model1=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="Kawasaki Z 800",bg="gray",fg="red")
                        model1.place(x=450,y=305)
                        model2=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="Kawasaki EN 500",bg="gray",fg="red")
                        model2.place(x=600,y=305)
                        model3=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="Kawasaki Ninja 250R",bg="gray",fg="red")
                        model3.place(x=750,y=305)
                        renk1=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="Kırmızı",bg="gray",fg="red")
                        renk1.place(x=450,y=455)
                        renk2=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="Beyaz",bg="gray",fg="red")
                        renk2.place(x=600,y=455)
                        renk3=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="Siyah",bg="gray",fg="red")
                        renk3.place(x=750,y=455)
                        fiyat1=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="1000 TL",bg="gray",fg="red")
                        fiyat1.place(x=450,y=605)
                        fiyat2=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="2000 TL",bg="gray",fg="red")
                        fiyat2.place(x=600,y=605)
                        fiyat3=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="3000 TL",bg="gray",fg="red")
                        fiyat3.place(x=750,y=605)
                        def cavazakiodemeekranı():
                            cavazakimotorodemeekranı=tk.Tk()
                            cavazakimotorodemeekranı.state("zoomed")
                            cavazakimotorodemeekranı.config(bg="gray")
                            cavazakimotorodemeekranı.title("Cavazaki Motor Ödeme Ekranı")
                            welcome_label=tk.Label(cavazakimotorodemeekranı,text="Ödeme Yapma Paneline Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                            welcome_label.place(x=400,y=100)
                            yazikartno=tk.Label(cavazakimotorodemeekranı,text="Kart No : ",font="Verdana 15", bg="red", fg="white",width=17)
                            yazikartno.place(x=230,y=300)
                            yazisonkullanımtarihi=tk.Label(cavazakimotorodemeekranı,text="Son Kullanım Tarihi : ",font="Verdana 15", bg="red", fg="white")
                            yazisonkullanımtarihi.place(x=230,y=400)
                            yazicvv=tk.Label(cavazakimotorodemeekranı,text="CVV : ",font="Verdana 15", bg="red", fg="white",width=17)
                            yazicvv.place(x=230,y=500)
                            kartnogirdi=tk.Entry(cavazakimotorodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            kartnogirdi.place(x=470, y=300, width=900, height=30)
                            sonkullanımtarihigirdi=tk.Entry(cavazakimotorodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            sonkullanımtarihigirdi.place(x=470, y=400, width=900, height=30)
                            cvvgirdi=tk.Entry(cavazakimotorodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            cvvgirdi.place(x=470, y=500, width=900, height=30)
                            def ödemecavazakimotoryazı():
                                yazicavazakimotorodemetamamlandı=tk.Label(cavazakimotorodemeekranı,text="ISLEMİNİZ BAŞARIYLA GERÇEKLEŞMİŞTİR.",font="Verdana 15", bg="red", fg="white",width=95,height=2)
                                yazicavazakimotorodemetamamlandı.place(x=200,y=565)
                            hondamotorodeme=tk.Button(cavazakimotorodemeekranı,text="Ödemeyi Tamamla",fg="red",bg="black",font="verdana 32",command=ödemecavazakimotoryazı)
                            hondamotorodeme.place(x=600,y=650)
                        cavazakimotorodemetamamlabuton=tk.Button(cavazakimotorozelliksecmeekranı,text="Ödeme Yap",fg="red",bg="black",font="verdana 32",command=cavazakiodemeekranı)
                        cavazakimotorodemetamamlabuton.place(x=1000,y=440)
                        cavazakimotorozelliksecmeekranı.mainloop()
                    self.__arac3=tk.Button(motoroptionsscreen,text="Cavazaki",fg="white",bg="black",font="verdana 32",command=cavazakiozelliksecmeekranı)
                    self.__arac3.place(x=400,y=600,width=800)
                    motoroptionsscreen.mainloop()
            motor=motor("","","")
            def kullanıcıekranı():
                kullanıcıekranı=tk.Tk()
                kullanıcıekranı.title("Kullanıcı ekranı")
                kullanıcıekranı.config(bg="gray")
                kullanıcıekranı.state("zoomed")
                welcomeyazıkullanıcıekranı=tk.Label(kullanıcıekranı,text="Kullanıcı Portalına hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                welcomeyazıkullanıcıekranı.place(x=440,y=150)
                butonaraba=tk.Button(kullanıcıekranı,text="Araba Seçenekleri",fg="white",bg="black",font="verdana 32",command=car.caroptions)
                butonaraba.place(x=300,y=400)
                butonmotor=tk.Button(kullanıcıekranı,text="Motor Seçenekleri",fg="white",bg="black",font="verdana 32",command=motor.motor_options)
                butonmotor.place(x=900,y=400)
                kullanıcıekranı.mainloop()
            kullanıcıekranı()    
    butongirişyap=tk.Button(userloginpanel,text="Giriş Yap",fg="white",bg="black",font="verdana 32",command=loginuser)
    butongirişyap.place(x=650,y=580)
    loginuser.mainloop()
def satıcıgirişpaneli():
    satıcıgirispaneli=tk.Tk()
    satıcıgirispaneli.state("zoomed")
    satıcıgirispaneli.config(bg="black")
    satıcıgirispaneli.title("Satıcı Giriş Paneli")
    satıcıgirişiwelcomeanaekran=tk.Label(satıcıgirispaneli,text="Satıcı Giriş Paneli",font="Verdana 64", bg="black", fg="red")
    satıcıgirişiwelcomeanaekran.place(x=400,y=100)
    yazikullanıcıadi=tk.Label(satıcıgirispaneli,text="Kullanıcı Adı : ",font="Verdana 15", bg="red", fg="white")
    yazikullanıcıadi.place(x=200,y=300)
    kullaniciadigirdi=tk.Entry(satıcıgirispaneli,bg="gray", fg="black", font="verdana 17 bold")
    kullaniciadigirdi.place(x=380, y=300, width=900, height=30)
    yazisifre=tk.Label(satıcıgirispaneli,text="Sifre : ",font="Verdana 15", bg="red", fg="white")
    yazisifre.place(x=200,y=450,width=150)
    sifregirdi=tk.Entry(satıcıgirispaneli,bg="gray", fg="black",font="verdana 17 bold")
    sifregirdi.place(x=380, y=450, width=900, height=30)
    
    def girişyapsatıcı():
        #We created dict to hold vendor information...
        satıcıbilgileri=dict()
        kullanıcıadı=kullaniciadigirdi.get()
        satıcıbilgileri["kullanıcı adı : "]=kullanıcıadı
        sifre=sifregirdi.get()
        satıcıbilgileri["Şifre : "]=sifre
        print(satıcıbilgileri)
        if satıcıbilgileri["kullanıcı adı : "]==kullanıcıadı and satıcıbilgileri["Şifre : "]==sifre:
            #This class is the parent of the car and motor class.
            class satıcı:
                # This method is created for constructor...
                def __init__(self,marka,model,depo,fiyat,renk):
                    self.__marka=marka
                    self.__model=model
                    self.__depo=depo
                    self.__fiyat=fiyat
                    self.__renk=renk 
            # This class is the engine child class and inherits from the vendor class...
            class motor(satıcı):
                kuruluş="Bu uygulamadaki veriler 2023 verileridir"
                # This method is created for constructor...
                def __init__(self,marka,model,depo,fiyat,renk):
                    super().__init__(marka,model,depo,fiyat,renk)    
                # It is the class method of our motorclass. It takes the cls parameter and is used to return any value in the class...
                @classmethod
                def motoruygulamasıhakkında(cls):
                    motor_paneli=tk.Tk()
                    motor_paneli.state("zoomed")
                    motor_paneli.title("Motorlu Araçlar Paneli")
                    motor_paneli.config(bg="gray")
                    welcome_label=tk.Label(motor_paneli,text="Motorlu Araçlar Paneline Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                    welcome_label.place(x=400,y=100)
                    buton1=tk.Button(motor_paneli,text="Motor Ekle",fg="white",bg="black",font="verdana 32",command=motor.motorbilgileriniekle)
                    buton1.place(x=450,y=300,height=80,width=700)
                    buton1=tk.Button(motor_paneli,text="Motor Bilgilerini Güncelle",fg="white",bg="black",font="verdana 32",command=motor.motorbilgileriniguncelle)
                    buton1.place(x=450,y=500,height=80,width=700)
                    print(cls.kuruluş)
                # This method takes engine information and also this method is a static method because there is no class value in this method.
                @staticmethod
                def motorbilgileriniekle():
                    motoreklepenceresi=tk.Tk()
                    motoreklepenceresi.state("zoomed")
                    motoreklepenceresi.title("Motor Bilgilerini Ekleme Ekranı")
                    motoreklepenceresi.config(bg="gray")
                    açılış_yazısı=tk.Label(motoreklepenceresi,text="Motor Ekleme Portalına Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                    açılış_yazısı.place(x=400,y=100)
                    yazi=tk.Label(motoreklepenceresi,text="Marka : ",font="Verdana 15", bg="red", fg="white")
                    yazi.place(x=230,y=280)
                    yazi_2=tk.Label(motoreklepenceresi,text="Model : ",font="Verdana 15", bg="red", fg="white")
                    yazi_2.place(x=230,y=330)
                    yazi_3=tk.Label(motoreklepenceresi,text="Depo : ",font="Verdana 15", bg="red", fg="white")
                    yazi_3.place(x=230,y=380)
                    yazi_4=tk.Label(motoreklepenceresi,text="Fiyat : ",font="Verdana 15", bg="red", fg="white")
                    yazi_4.place(x=230,y=430)
                    yazi_5=tk.Label(motoreklepenceresi,text="Renk : ",font="Verdana 15", bg="red", fg="white")
                    yazi_5.place(x=230,y=480)
                    marka=tk.Entry(motoreklepenceresi,bg="white", fg="black", font="verdana 17 bold")
                    marka.place(x=330, y=280, width=900, height=30)
                    model=tk.Entry(motoreklepenceresi,bg="white",fg="black",font="verdana 17 bold")
                    model.place(x=330, y=330, width=900, height=30)
                    depo=tk.Entry(motoreklepenceresi,bg="white",fg="black",font="verdana 17 bold")
                    depo.place(x=330, y=380, width=900, height=30)
                    fiyat=tk.Entry(motoreklepenceresi,bg="white",fg="black",font="verdana 17 bold")
                    fiyat.place(x=330, y=430, width=900, height=30)
                    renk=tk.Entry(motoreklepenceresi,bg="white",fg="black",font="verdana 17 bold")
                    renk.place(x=330, y=480, width=900, height=30)
                    def eklemeyazısı():
                        açılış_yazısı=tk.Label(motoreklepenceresi,text="Tüm Bilgiler Veri Tabanına Eklenmiştir...",font="Verdana 32", bg="red", fg="white")
                        açılış_yazısı.place(x=300,y=560)
                    buton1=tk.Button(motoreklepenceresi,text="Oluştur",fg="white",bg="black",font="verdana 32",command=eklemeyazısı)
                    buton1.place(x=650,y=640)
                #This method updates motorcycle information...
                def motorbilgileriniguncelle(self):
                    motor_guncelleme_penceresi=tk.Tk()
                    motor_guncelleme_penceresi.state("zoomed")
                    motor_guncelleme_penceresi.title("Motor Bilgilerini Güncelleme Ekranı")
                    motor_guncelleme_penceresi.config(bg="gray")
                    yazi=tk.Label(motor_guncelleme_penceresi,text="Motor Bilgilerini Güncelleme Portalına Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                    yazi.place(x=250,y=150)
                    self.yazi=tk.Label(motor_guncelleme_penceresi,text="Güncellenecek Bölüm : ",font="Verdana 15", bg="red", fg="white")
                    self.yazi.place(x=130,y=300)
                    key=tk.Entry(motor_guncelleme_penceresi,bg="white", fg="black", font="verdana 17 bold")
                    key.place(x=400, y=300, width=900, height=30)
                    value=tk.Label(motor_guncelleme_penceresi,text="Yeni Değer : ",font="Verdana 15", bg="red", fg="white")
                    value.place(x=130,y=450,width=250)
                    value=tk.Entry(motor_guncelleme_penceresi,bg="white", fg="black", font="verdana 17 bold")
                    value.place(x=400, y=450, width=900, height=30)
                    def eklemeyazısı2():
                        uyarı=tk.Label(motor_guncelleme_penceresi,text="Yeni bilgiler veri tabanına kaydedilmiştir...",font="Verdana 32", bg="red", fg="white")
                        uyarı.place(x=350,y=530)
                    
                    butonduzenle=tk.Button(motor_guncelleme_penceresi,text="Düzenle",fg="white",bg="black",font="verdana 32",command=eklemeyazısı2)
                    butonduzenle.place(x=650,y=630)
            motor=motor("","",100,1000,"")
            # This class is the car class and inherits from the seller class...
            class araba(satıcı):
                def __init__(self, marka, model,depo,fiyat,renk):
                    super().__init__(marka, model,depo,fiyat,renk)
                # This method is coded to create the car add screen...
                def arababilgileriniekle(self):
                    araba_ekle_penceresi=tk.Tk()
                    araba_ekle_penceresi.state("zoomed")
                    araba_ekle_penceresi.title("Araba ekleme ekranı")
                    araba_ekle_penceresi.config(bg="gray")
                    açılış_yazısı=tk.Label(araba_ekle_penceresi,text="Araba Ekleme Portalına Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                    açılış_yazısı.place(x=400,y=100)
                    self.yazi=tk.Label(araba_ekle_penceresi,text="Marka : ",font="Verdana 15", bg="red", fg="white")
                    self.yazi.place(x=230,y=280)
                    self.yazi_2=tk.Label(araba_ekle_penceresi,text="Model : ",font="Verdana 15", bg="red", fg="white")
                    self.yazi_2.place(x=230,y=330)
                    self.yazi_3=tk.Label(araba_ekle_penceresi,text="Depo : ",font="Verdana 15", bg="red", fg="white")
                    self.yazi_3.place(x=230,y=380)
                    self.yazi_4=tk.Label(araba_ekle_penceresi,text="Fiyat : ",font="Verdana 15", bg="red", fg="white")
                    self.yazi_4.place(x=230,y=430)
                    self.yazi_5=tk.Label(araba_ekle_penceresi,text="Renk : ",font="Verdana 15", bg="red", fg="white")
                    self.yazi_5.place(x=230,y=480)
                    self.__marka=tk.Entry(araba_ekle_penceresi,bg="white", fg="black", font="verdana 17 bold")
                    self.__marka.place(x=330, y=280, width=900, height=30)
                    self.__model=tk.Entry(araba_ekle_penceresi,bg="white",fg="black",font="verdana 17 bold")
                    self.__model.place(x=330, y=330, width=900, height=30)
                    self.__depo=tk.Entry(araba_ekle_penceresi,bg="white",fg="black",font="verdana 17 bold")
                    self.__depo.place(x=330, y=380, width=900, height=30)
                    self.__fiyat=tk.Entry(araba_ekle_penceresi,bg="white",fg="black",font="verdana 17 bold")
                    self.__fiyat.place(x=330, y=430, width=900, height=30)
                    self.__renk=tk.Entry(araba_ekle_penceresi,bg="white",fg="black",font="verdana 17 bold")
                    self.__renk.place(x=330, y=480, width=900, height=30)
                    def eklemeyazısı():
                        açılış_yazısı=tk.Label(araba_ekle_penceresi,text="Tüm Bilgiler Veri Tabanına Eklenmiştir...",font="Verdana 32", bg="red", fg="white")
                        açılış_yazısı.place(x=300,y=530)
                    buton1=tk.Button(araba_ekle_penceresi,text="Oluştur",fg="white",bg="black",font="verdana 32",command=eklemeyazısı)
                    buton1.place(x=650,y=600)
                # This method was created to create a car update screen...
                def arababilgileriniguncelle(self):
                    araba_guncelleme_penceresi=tk.Tk()
                    araba_guncelleme_penceresi.state("zoomed")
                    araba_guncelleme_penceresi.title("Araba güncelleme ekranı")
                    araba_guncelleme_penceresi.config(bg="gray")
                    yazihosgeldin=tk.Label(araba_guncelleme_penceresi,text="Araba Guncelleme Portalına Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                    yazihosgeldin.place(x=350,y=150)
                    guncelenecekdeğer=tk.Label(araba_guncelleme_penceresi,text="Güncellenecek Bölüm : ",font="Verdana 15", bg="red", fg="white")
                    guncelenecekdeğer.place(x=180,y=300)
                    guncelenecekdeğer=tk.Entry(araba_guncelleme_penceresi,bg="white", fg="black", font="verdana 17 bold")
                    guncelenecekdeğer.place(x=450, y=300, width=900, height=30)
                    gunceldeger=tk.Label(araba_guncelleme_penceresi,text="Yeni Değer : ",font="Verdana 15", bg="red", fg="white")
                    gunceldeger.place(x=180,y=450,width=240)
                    gunceldegergiris=tk.Entry(araba_guncelleme_penceresi,bg="white", fg="black", font="verdana 17 bold")
                    gunceldegergiris.place(x=450, y=450, width=900, height=30)
                    def eklemeyazısı2():
                        self.yazi=tk.Label(araba_guncelleme_penceresi,text="Yeni bilgiler veri tabanına kaydedilmiştir...",font="Verdana 32", bg="red", fg="white")
                        self.yazi.place(x=350,y=515)
                    
                    buton1=tk.Button(araba_guncelleme_penceresi,text="Düzenle",fg="white",bg="black",font="verdana 32",command=eklemeyazısı2)
                    buton1.place(x=650,y=600)
            araba=araba("",0,0,0,"kırmızı")
            def araba_işlemleri():
                iç_pencere_araba=tk.Tk()
                iç_pencere_araba.title("Araba İşlemleri")
                iç_pencere_araba.state("zoomed")
                iç_pencere_araba.config(bg="gray")
                yazi=tk.Label(iç_pencere_araba,text="Araba işlemleri Portalına hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                yazi.place(x=400,y=100)
                buton1=tk.Button(iç_pencere_araba,text="Araba Ekle",fg="white",bg="black",font="verdana 32",command=araba.arababilgileriniekle)
                buton1.place(x=650,y=300)
                buton2=tk.Button(iç_pencere_araba,text="Araba Bilgilerini güncelle",fg="white",bg="black",font="verdana 32",command=araba.arababilgileriniguncelle)
                buton2.place(x=500,y=500)
                iç_pencere_araba.mainloop()
            # This method is created for vendor portal...
            def uygulama():
                satıcı_penceresi=tk.Tk()
                satıcı_penceresi.title("Satıcı Portalı")
                satıcı_penceresi.state("zoomed")
                satıcı_penceresi.config(bg="gray")
                yazi=tk.Label(satıcı_penceresi,text="Satıcı Portalına hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                yazi.place(x=475,y=200)
                buton1=tk.Button(satıcı_penceresi,text="Araba İşlemleri",fg="white",bg="black",font="verdana 32",command=araba_işlemleri)
                buton1.place(x=250,y=400)
                buton2=tk.Button(satıcı_penceresi,text="Motor İşlemleri",fg="white",bg="black",font="verdana 32",command=motor.motoruygulamasıhakkında)
                buton2.place(x=900,y=400)
                satıcı_penceresi.mainloop()
            uygulama()
    butongirişyap=tk.Button(satıcıgirispaneli,text="Giriş Yap",fg="white",bg="black",font="verdana 32",command=girişyapsatıcı)
    butongirişyap.place(x=650,y=580)
# This class is a parent class inherited from our main screen child class...
class ekran:
    def __init__(self,welcomeanaekran,kullanıcıgirişibuton,satıcıgirişibuton,çıkışbuton,anaekran):
        self.__welcomeanaekran=welcomeanaekran
        self.__kullanıcıgirişibuton=kullanıcıgirişibuton
        self.__satıcıgirişibuton=satıcıgirişibuton
        self.__çıkışbuton=çıkışbuton
        self.__anaekran=anaekran
    
        
# This class inherits from our display parent class...
class anaekran(ekran):
        def __init__(self, welcomeanaekran, kullanıcıgirişibuton, satıcıgirişibuton, çıkışbuton, anaekran):
            super().__init__(welcomeanaekran, kullanıcıgirişibuton, satıcıgirişibuton, çıkışbuton, anaekran)    
        def mainwindow(self):
            self.__anaekran=tk.Tk()
            self.__anaekran.state("zoomed")
            self.__anaekran.config(bg="black")
            self.__anaekran.title("Rent A Car")
            self.__welcomemainscreen=tk.Label(self.__anaekran,text="Kirala Götür",font="Verdana 64", bg="black", fg="red")
            self.__welcomemainscreen.place(x=530,y=100)
            self.__kullanıcıgirişibuton=tk.Button(self.__anaekran,text="Kullanıcı Girişi",fg="black",bg="gray",font="verdana 32",command=userloginpanel)
            self.__kullanıcıgirişibuton.place(x=450,y=300,height=80,width=700)
            self.__satıcıgirişibuton=tk.Button(self.__anaekran,text="Satıcı Girişi",fg="black",bg="gray",font="verdana 32",command=satıcıgirişpaneli)
            self.__satıcıgirişibuton.place(x=450,y=450,height=80,width=700)
            self.__cikisbuton=tk.Button(self.__anaekran,text="Çıkış Yap",fg="black",bg="gray",font="verdana 32",command=self.__anaekran.destroy)
            self.__cikisbuton.place(x=450,y=600,height=80,width=700)
            self.__anaekran.mainloop()
anaekran=anaekran(0,0,0,0,0)
anaekran.mainwindow()
