import tkinter as tk
def kullanıcıgirispaneli():
    kullanıcıgirispaneli=tk.Tk()
    kullanıcıgirispaneli.state("zoomed")
    kullanıcıgirispaneli.config(bg="black")
    kullanıcıgirispaneli.title("Kullanıcı Giriş Paneli")
    kullanıcıgirişiwelcomeanaekran=tk.Label(kullanıcıgirispaneli,text="Kullanıcı Giriş Paneli",font="Verdana 64", bg="black", fg="red")
    kullanıcıgirişiwelcomeanaekran.place(x=320,y=100)
    yazikullanıcıadi=tk.Label(kullanıcıgirispaneli,text="Kullanıcı Adı : ",font="Verdana 15", bg="red", fg="white")
    yazikullanıcıadi.place(x=200,y=300)
    kullaniciadigirdi=tk.Entry(kullanıcıgirispaneli,bg="gray", fg="black", font="verdana 17 bold")
    kullaniciadigirdi.place(x=380, y=300, width=900, height=30)
    yazisifre=tk.Label(kullanıcıgirispaneli,text="Sifre : ",font="Verdana 15", bg="red", fg="white")
    yazisifre.place(x=200,y=450,width=150)
    sifregirdi=tk.Entry(kullanıcıgirispaneli,bg="gray", fg="black",font="verdana 17 bold")
    sifregirdi.place(x=380, y=450, width=900, height=30)
    def girişyapkullanıcı():
        # We have defined a list to hold user information.
        kullanıcıbilgileri=list()
        kullanıcıadı=kullaniciadigirdi.get()
        kullanıcıbilgileri.append(kullanıcıadı)
        sifre=sifregirdi.get()
        kullanıcıbilgileri.append(sifre)
        print(kullanıcıbilgileri)
        if kullanıcıadı in kullanıcıbilgileri and sifre in kullanıcıbilgileri:
            # This is our parent class that inherited the car and motor class...
            
            class kullanıcı():
                def __init__(self,arac1,arac2,arac3):
                    self.__arac1=arac1
                    self.__arac2=arac2
                    self.__arac3=arac3
                
                
            # This class is a child class that inherits from our user class...
            class araba(kullanıcı):
                def __init__(self, arac1, arac2, arac3):
                    super().__init__(arac1, arac2, arac3)
                def arabaseçenekleri(self):
                    arabaseçenekleri=tk.Tk()
                    arabaseçenekleri.title("Araba seçeneklerimiz")
                    arabaseçenekleri.config(bg="gray")
                    arabaseçenekleri.state("zoomed")
                    welcomeyazıkullanıcıekranı=tk.Label(arabaseçenekleri,text="Araba Seçeneklerimiz",font="Verdana 32", bg="red", fg="white")
                    welcomeyazıkullanıcıekranı.place(x=580,y=100)
                    def bmvozelliksec():
                        bmvozelliksecmeekranı=tk.Tk()
                        bmvozelliksecmeekranı.state("zoomed")
                        bmvozelliksecmeekranı.config(bg="gray")
                        bmvozelliksecmeekranı.title("Bmv Özellik Seçme Ekranı")
                        yazibmvozellik=tk.Label(bmvozelliksecmeekranı,text="Bmv Özellik Seçme Ekranı",font="Verdana 32", bg="red", fg="white")
                        yazibmvozellik.place(x=475,y=100)
                        yazimodel=tk.Label(bmvozelliksecmeekranı,text="Model : ",font="Verdana 16", bg="red", fg="white")
                        yazimodel.place(x=300,y=300)
                        yazirenk=tk.Label(bmvozelliksecmeekranı,text="Renk : ",font="Verdana 16", bg="red", fg="white")
                        yazirenk.place(x=300,y=450)
                        yazifiyat=tk.Label(bmvozelliksecmeekranı,text="Fiyat : ",font="Verdana 16", bg="red", fg="white")
                        yazifiyat.place(x=300,y=600)
                        model1=tk.Checkbutton(bmvozelliksecmeekranı,text="320",bg="gray",fg="red")
                        model1.place(x=450,y=305)
                        model2=tk.Checkbutton(bmvozelliksecmeekranı,text="520",bg="gray",fg="red")
                        model2.place(x=600,y=305,width=30)
                        model3=tk.Checkbutton(bmvozelliksecmeekranı,text="820",bg="gray",fg="red")
                        model3.place(x=750,y=305)
                        renk1=tk.Checkbutton(bmvozelliksecmeekranı,text="Kırmızı",bg="gray",fg="red")
                        renk1.place(x=450,y=455)
                        renk2=tk.Checkbutton(bmvozelliksecmeekranı,text="Beyaz",bg="gray",fg="red")
                        renk2.place(x=600,y=455)
                        renk3=tk.Checkbutton(bmvozelliksecmeekranı,text="Siyah",bg="gray",fg="red")
                        renk3.place(x=750,y=455)
                        fiyat1=tk.Checkbutton(bmvozelliksecmeekranı,text="1000 TL",bg="gray",fg="red")
                        fiyat1.place(x=450,y=605)
                        fiyat2=tk.Checkbutton(bmvozelliksecmeekranı,text="2000 TL",bg="gray",fg="red")
                        fiyat2.place(x=600,y=605)
                        fiyat3=tk.Checkbutton(bmvozelliksecmeekranı,text="3000 TL",bg="gray",fg="red")
                        fiyat3.place(x=750,y=605)
                        def ödemebmv():
                            bmvodemeekranı=tk.Tk()
                            bmvodemeekranı.state("zoomed")
                            bmvodemeekranı.config(bg="gray")
                            bmvodemeekranı.title("Bmv Ödeme Ekranı")
                            welcome_label=tk.Label(bmvodemeekranı,text="Ödeme Yapma Paneline Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                            welcome_label.place(x=400,y=100)
                            yazikartno=tk.Label(bmvodemeekranı,text="Kart No : ",font="Verdana 15", bg="red", fg="white",width=17)
                            yazikartno.place(x=230,y=300)
                            yazisonkullanımtarihi=tk.Label(bmvodemeekranı,text="Son Kullanım Tarihi : ",font="Verdana 15", bg="red", fg="white")
                            yazisonkullanımtarihi.place(x=230,y=400)
                            yazicvv=tk.Label(bmvodemeekranı,text="CVV : ",font="Verdana 15", bg="red", fg="white",width=17)
                            yazicvv.place(x=230,y=500)
                            kartnogirdi=tk.Entry(bmvodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            kartnogirdi.place(x=470, y=300, width=900, height=30)
                            sonkullanımtarihigirdi=tk.Entry(bmvodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            sonkullanımtarihigirdi.place(x=470, y=400, width=900, height=30)
                            cvvgirdi=tk.Entry(bmvodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            cvvgirdi.place(x=470, y=500, width=900, height=30)
                            def odemetamamlandıyazısı():
                                yaziodemetamamlandı=tk.Label(bmvodemeekranı,text="ISLEMİNİZ BAŞARIYLA GERÇEKLEŞMİŞTİR.",font="Verdana 15", bg="red", fg="white",width=95,height=2)
                                yaziodemetamamlandı.place(x=200,y=565)
                            bmvodemetamamlabuton=tk.Button(bmvodemeekranı,text="Ödemeyi tamamla",fg="red",bg="black",font="verdana 32",command=odemetamamlandıyazısı)
                            bmvodemetamamlabuton.place(x=600,y=650)
                            bmvodemeekranı.mainloop()
                        bmvodeme=tk.Button(bmvozelliksecmeekranı,text="Ödeme Yap",fg="red",bg="black",font="verdana 32",command=ödemebmv)
                        bmvodeme.place(x=970,y=420)
                    self.__arac1=tk.Button(arabaseçenekleri,text="BMV",fg="white",bg="black",font="verdana 32",command=bmvozelliksec)
                    self.__arac1.place(x=400,y=300,width=800)
                    def audiozelliksec():
                        audiozelliksecmeekranı=tk.Tk()
                        audiozelliksecmeekranı.state("zoomed")
                        audiozelliksecmeekranı.config(bg="gray")
                        audiozelliksecmeekranı.title("Audi Özellik Seçme Ekranı")
                        yaziaudiozellik=tk.Label(audiozelliksecmeekranı,text="Audi Özellik Seçme Ekranı",font="Verdana 32", bg="red", fg="white")
                        yaziaudiozellik.place(x=475,y=100)
                        yazimodel=tk.Label(audiozelliksecmeekranı,text="Model : ",font="Verdana 16", bg="red", fg="white")
                        yazimodel.place(x=300,y=300)
                        yazirenk=tk.Label(audiozelliksecmeekranı,text="Renk : ",font="Verdana 16", bg="red", fg="white")
                        yazirenk.place(x=300,y=450)
                        yazifiyat=tk.Label(audiozelliksecmeekranı,text="Fiyat : ",font="Verdana 16", bg="red", fg="white")
                        yazifiyat.place(x=300,y=600)
                        model1=tk.Checkbutton(audiozelliksecmeekranı,text="A3",bg="gray",fg="red")
                        model1.place(x=450,y=305)
                        model2=tk.Checkbutton(audiozelliksecmeekranı,text="A5",bg="gray",fg="red")
                        model2.place(x=600,y=305,width=30)
                        model3=tk.Checkbutton(audiozelliksecmeekranı,text="A6",bg="gray",fg="red")
                        model3.place(x=750,y=305)
                        renk1=tk.Checkbutton(audiozelliksecmeekranı,text="Kırmızı",bg="gray",fg="red")
                        renk1.place(x=450,y=455)
                        renk2=tk.Checkbutton(audiozelliksecmeekranı,text="Beyaz",bg="gray",fg="red")
                        renk2.place(x=600,y=455)
                        renk3=tk.Checkbutton(audiozelliksecmeekranı,text="Siyah",bg="gray",fg="red")
                        renk3.place(x=750,y=455)
                        fiyat1=tk.Checkbutton(audiozelliksecmeekranı,text="1000 TL",bg="gray",fg="red")
                        fiyat1.place(x=450,y=605)
                        fiyat2=tk.Checkbutton(audiozelliksecmeekranı,text="2000 TL",bg="gray",fg="red")
                        fiyat2.place(x=600,y=605)
                        fiyat3=tk.Checkbutton(audiozelliksecmeekranı,text="3000 TL",bg="gray",fg="red")
                        fiyat3.place(x=750,y=605)
                        audiodemetamamlabuton=tk.Button(audiozelliksecmeekranı,text="Ödeme Yap",fg="red",bg="black",font="verdana 32",command=audiodemeekranı)
                        audiodemetamamlabuton.place(x=1000,y=440)
                    def audiodemeekranı():
                                    audiodemeekranı=tk.Tk()
                                    audiodemeekranı.state("zoomed")
                                    audiodemeekranı.config(bg="gray")
                                    audiodemeekranı.title("Audi Ödeme Ekranı")
                                    welcome_label=tk.Label(audiodemeekranı,text="Ödeme Yapma Paneline Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                                    welcome_label.place(x=400,y=100)
                                    yazikartno=tk.Label(audiodemeekranı,text="Kart No : ",font="Verdana 15", bg="red", fg="white",width=17)
                                    yazikartno.place(x=230,y=300)
                                    yazisonkullanımtarihi=tk.Label(audiodemeekranı,text="Son Kullanım Tarihi : ",font="Verdana 15", bg="red", fg="white")
                                    yazisonkullanımtarihi.place(x=230,y=400)
                                    yazicvv=tk.Label(audiodemeekranı,text="CVV : ",font="Verdana 15", bg="red", fg="white",width=17)
                                    yazicvv.place(x=230,y=500)
                                    kartnogirdi=tk.Entry(audiodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                                    kartnogirdi.place(x=470, y=300, width=900, height=30)
                                    sonkullanımtarihigirdi=tk.Entry(audiodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                                    sonkullanımtarihigirdi.place(x=470, y=400, width=900, height=30)
                                    cvvgirdi=tk.Entry(audiodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                                    cvvgirdi.place(x=470, y=500, width=900, height=30)    
                                    
                                    def ödemeaudiyazı():
                                        yaziodemetamamlandı=tk.Label(audiodemeekranı,text="ISLEMİNİZ BAŞARIYLA GERÇEKLEŞMİŞTİR.",font="Verdana 15", bg="red", fg="white",width=95,height=2)
                                        yaziodemetamamlandı.place(x=200,y=565)
                                    audiodeme=tk.Button(audiodemeekranı,text="Ödemeyi Tamamla",fg="red",bg="black",font="verdana 32",command=ödemeaudiyazı)
                                    audiodeme.place(x=600,y=650)

                    self.__arac2=tk.Button(arabaseçenekleri,text="Audi",fg="white",bg="black",font="verdana 32",command=audiozelliksec)
                    self.__arac2.place(x=400,y=450,width=800)
                    def mersedesozelliksecme():
                        mersedesozelliksecmeekranı=tk.Tk()
                        mersedesozelliksecmeekranı.state("zoomed")
                        mersedesozelliksecmeekranı.config(bg="gray")
                        mersedesozelliksecmeekranı.title("Mersedes Özellik Seçme Ekranı")
                        yazimersedesozellik=tk.Label(mersedesozelliksecmeekranı,text="Mersedes Özellik Seçme Ekranı",font="Verdana 32", bg="red", fg="white")
                        yazimersedesozellik.place(x=475,y=100)
                        yazimodel=tk.Label(mersedesozelliksecmeekranı,text="Model : ",font="Verdana 16", bg="red", fg="white")
                        yazimodel.place(x=300,y=300)
                        yazirenk=tk.Label(mersedesozelliksecmeekranı,text="Renk : ",font="Verdana 16", bg="red", fg="white")
                        yazirenk.place(x=300,y=450)
                        yazifiyat=tk.Label(mersedesozelliksecmeekranı,text="Fiyat : ",font="Verdana 16", bg="red", fg="white")
                        yazifiyat.place(x=300,y=600)
                        model1=tk.Checkbutton(mersedesozelliksecmeekranı,text="C180",bg="gray",fg="red")
                        model1.place(x=450,y=305)
                        model2=tk.Checkbutton(mersedesozelliksecmeekranı,text="A200",bg="gray",fg="red")
                        model2.place(x=600,y=305,width=30)
                        model3=tk.Checkbutton(mersedesozelliksecmeekranı,text="G63",bg="gray",fg="red")
                        model3.place(x=750,y=305)
                        renk1=tk.Checkbutton(mersedesozelliksecmeekranı,text="Kırmızı",bg="gray",fg="red")
                        renk1.place(x=450,y=455)
                        renk2=tk.Checkbutton(mersedesozelliksecmeekranı,text="Beyaz",bg="gray",fg="red")
                        renk2.place(x=600,y=455)
                        renk3=tk.Checkbutton(mersedesozelliksecmeekranı,text="Siyah",bg="gray",fg="red")
                        renk3.place(x=750,y=455)
                        fiyat1=tk.Checkbutton(mersedesozelliksecmeekranı,text="1000 TL",bg="gray",fg="red")
                        fiyat1.place(x=450,y=605)
                        fiyat2=tk.Checkbutton(mersedesozelliksecmeekranı,text="2000 TL",bg="gray",fg="red")
                        fiyat2.place(x=600,y=605)
                        fiyat3=tk.Checkbutton(mersedesozelliksecmeekranı,text="3000 TL",bg="gray",fg="red")
                        fiyat3.place(x=750,y=605)
                        def mersedesodemeekranı():
                            mersedesodemeekranı=tk.Tk()
                            mersedesodemeekranı.state("zoomed")
                            mersedesodemeekranı.config(bg="gray")
                            mersedesodemeekranı.title("Mersedes Ödeme Ekranı")
                            welcome_label=tk.Label(mersedesodemeekranı,text="Ödeme Yapma Paneline Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                            welcome_label.place(x=400,y=100)
                            yazikartno=tk.Label(mersedesodemeekranı,text="Kart No : ",font="Verdana 15", bg="red", fg="white",width=17)
                            yazikartno.place(x=230,y=300)
                            yazisonkullanımtarihi=tk.Label(mersedesodemeekranı,text="Son Kullanım Tarihi : ",font="Verdana 15", bg="red", fg="white")
                            yazisonkullanımtarihi.place(x=230,y=400)
                            yazicvv=tk.Label(mersedesodemeekranı,text="CVV : ",font="Verdana 15", bg="red", fg="white",width=17)
                            yazicvv.place(x=230,y=500)
                            kartnogirdi=tk.Entry(mersedesodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            kartnogirdi.place(x=470, y=300, width=900, height=30)
                            sonkullanımtarihigirdi=tk.Entry(mersedesodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            sonkullanımtarihigirdi.place(x=470, y=400, width=900, height=30)
                            cvvgirdi=tk.Entry(mersedesodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            cvvgirdi.place(x=470, y=500, width=900, height=30)
                            def ödemeaudiyazı():
                                yaziodemetamamlandı=tk.Label(mersedesodemeekranı,text="ISLEMİNİZ BAŞARIYLA GERÇEKLEŞMİŞTİR.",font="Verdana 15", bg="red", fg="white",width=95,height=2)
                                yaziodemetamamlandı.place(x=200,y=565)
                            mersedesodeme=tk.Button(mersedesodemeekranı,text="Ödemeyi Tamamla",fg="red",bg="black",font="verdana 32",command=ödemeaudiyazı)
                            mersedesodeme.place(x=600,y=650)

                        mersedesodemetamamlabuton=tk.Button(mersedesozelliksecmeekranı,text="Ödeme Yap",fg="red",bg="black",font="verdana 32",command=mersedesodemeekranı)
                        mersedesodemetamamlabuton.place(x=1000,y=440)
                        mersedesozelliksecmeekranı.mainloop()
                    self.__arac3=tk.Button(arabaseçenekleri,text="Mercedes",fg="white",bg="black",font="verdana 32",command=mersedesozelliksecme)
                    self.__arac3.place(x=400,y=600,width=800)
                    arabaseçenekleri.mainloop()
            araba=araba("","","")
            # This class is a child class that inherits from our user class...
            class motor(kullanıcı):
                def __init__(self, arac1, arac2, arac3):
                    super().__init__(arac1, arac2, arac3)
                def motor_seçeneklerimiz(self):
                    motorseçenekleripenceresi=tk.Tk()
                    motorseçenekleripenceresi.title("Motor Seçeneklerimiz")
                    motorseçenekleripenceresi.config(bg="gray")
                    motorseçenekleripenceresi.state("zoomed")
                    welcomeyazıkullanıcıekranı=tk.Label(motorseçenekleripenceresi,text="Motor Seçeneklerimiz",font="Verdana 32", bg="red", fg="white")
                    welcomeyazıkullanıcıekranı.place(x=530,y=100)
                    def bmvmotorozelliksecmeekranı():
                        bmvmotorozelliksecmeekranı=tk.Tk()
                        bmvmotorozelliksecmeekranı.title("Bmv Motor Özellikleri Seçme Ekranı")
                        bmvmotorozelliksecmeekranı.config(bg="gray")
                        bmvmotorozelliksecmeekranı.state("zoomed")
                        yazibmvozellik=tk.Label(bmvmotorozelliksecmeekranı,text="Bmv Özellik Seçme Ekranı",font="Verdana 32", bg="red", fg="white")
                        yazibmvozellik.place(x=475,y=100)
                        yazimodel=tk.Label(bmvmotorozelliksecmeekranı,text="Model : ",font="Verdana 16", bg="red", fg="white")
                        yazimodel.place(x=300,y=300)
                        yazirenk=tk.Label(bmvmotorozelliksecmeekranı,text="Renk : ",font="Verdana 16", bg="red", fg="white")
                        yazirenk.place(x=300,y=450)
                        yazifiyat=tk.Label(bmvmotorozelliksecmeekranı,text="Fiyat : ",font="Verdana 16", bg="red", fg="white")
                        yazifiyat.place(x=300,y=600)
                        model1=tk.Checkbutton(bmvmotorozelliksecmeekranı,text="R 1250 GS",bg="gray",fg="red")
                        model1.place(x=450,y=305)
                        model2=tk.Checkbutton(bmvmotorozelliksecmeekranı,text="S 1000 XR",bg="gray",fg="red")
                        model2.place(x=600,y=305)
                        model3=tk.Checkbutton(bmvmotorozelliksecmeekranı,text="F 900 XR",bg="gray",fg="red")
                        model3.place(x=750,y=305)
                        renk1=tk.Checkbutton(bmvmotorozelliksecmeekranı,text="Kırmızı",bg="gray",fg="red")
                        renk1.place(x=450,y=455)
                        renk2=tk.Checkbutton(bmvmotorozelliksecmeekranı,text="Beyaz",bg="gray",fg="red")
                        renk2.place(x=600,y=455)
                        renk3=tk.Checkbutton(bmvmotorozelliksecmeekranı,text="Siyah",bg="gray",fg="red")
                        renk3.place(x=750,y=455)
                        fiyat1=tk.Checkbutton(bmvmotorozelliksecmeekranı,text="1000 TL",bg="gray",fg="red")
                        fiyat1.place(x=450,y=605)
                        fiyat2=tk.Checkbutton(bmvmotorozelliksecmeekranı,text="2000 TL",bg="gray",fg="red")
                        fiyat2.place(x=600,y=605)
                        fiyat3=tk.Checkbutton(bmvmotorozelliksecmeekranı,text="3000 TL",bg="gray",fg="red")
                        fiyat3.place(x=750,y=605)
                        def bmvmotorodeme():
                            bmvmotorodemeekranı=tk.Tk()
                            bmvmotorodemeekranı.state("zoomed")
                            bmvmotorodemeekranı.config(bg="gray")
                            bmvmotorodemeekranı.title("Bmv Motor Ödeme Ekranı")
                            welcome_label=tk.Label(bmvmotorodemeekranı,text="Ödeme Yapma Paneline Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                            welcome_label.place(x=400,y=100)
                            yazikartno=tk.Label(bmvmotorodemeekranı,text="Kart No : ",font="Verdana 15", bg="red", fg="white",width=17)
                            yazikartno.place(x=230,y=300)
                            yazisonkullanımtarihi=tk.Label(bmvmotorodemeekranı,text="Son Kullanım Tarihi : ",font="Verdana 15", bg="red", fg="white")
                            yazisonkullanımtarihi.place(x=230,y=400)
                            yazicvv=tk.Label(bmvmotorodemeekranı,text="CVV : ",font="Verdana 15", bg="red", fg="white",width=17)
                            yazicvv.place(x=230,y=500)
                            kartnogirdi=tk.Entry(bmvmotorodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            kartnogirdi.place(x=470, y=300, width=900, height=30)
                            sonkullanımtarihigirdi=tk.Entry(bmvmotorodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            sonkullanımtarihigirdi.place(x=470, y=400, width=900, height=30)
                            cvvgirdi=tk.Entry(bmvmotorodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            cvvgirdi.place(x=470, y=500, width=900, height=30)
                            def ödemebmvmotoryazı():
                                yazibmvmotorodemetamamlandı=tk.Label(bmvmotorodemeekranı,text="ISLEMİNİZ BAŞARIYLA GERÇEKLEŞMİŞTİR.",font="Verdana 15", bg="red", fg="white",width=95,height=2)
                                yazibmvmotorodemetamamlandı.place(x=200,y=565)
                            bmvmotorodeme=tk.Button(bmvmotorodemeekranı,text="Ödemeyi Tamamla",fg="red",bg="black",font="verdana 32",command=ödemebmvmotoryazı)
                            bmvmotorodeme.place(x=600,y=650)
                        bmvmotorodemetamamlabuton=tk.Button(bmvmotorozelliksecmeekranı,text="Ödeme Yap",fg="red",bg="black",font="verdana 32",command=bmvmotorodeme)
                        bmvmotorodemetamamlabuton.place(x=1000,y=440)  
                    self.__arac1=tk.Button(motorseçenekleripenceresi,text="BMV",fg="white",bg="black",font="verdana 32",command=bmvmotorozelliksecmeekranı)
                    self.__arac1.place(x=400,y=300,width=800)
                    def hondamotorozellikseçmeişlemiyap():
                        hondamotorozelliksecmeekranı=tk.Tk()
                        hondamotorozelliksecmeekranı.title("Honda Motor Özellikleri Seçme Ekranı")
                        hondamotorozelliksecmeekranı.config(bg="gray")
                        hondamotorozelliksecmeekranı.state("zoomed")
                        yazihondamotorozellik=tk.Label(hondamotorozelliksecmeekranı,text="Honda Özellik Seçme Ekranı",font="Verdana 32", bg="red", fg="white")
                        yazihondamotorozellik.place(x=475,y=100)
                        yazimodel=tk.Label(hondamotorozelliksecmeekranı,text="Model : ",font="Verdana 16", bg="red", fg="white")
                        yazimodel.place(x=300,y=300)
                        yazirenk=tk.Label(hondamotorozelliksecmeekranı,text="Renk : ",font="Verdana 16", bg="red", fg="white")
                        yazirenk.place(x=300,y=450)
                        yazifiyat=tk.Label(hondamotorozelliksecmeekranı,text="Fiyat : ",font="Verdana 16", bg="red", fg="white")
                        yazifiyat.place(x=300,y=600)
                        model1=tk.Checkbutton(hondamotorozelliksecmeekranı,text="Activa S",bg="gray",fg="red")
                        model1.place(x=450,y=305)
                        model2=tk.Checkbutton(hondamotorozelliksecmeekranı,text="PCX 125",bg="gray",fg="red")
                        model2.place(x=600,y=305)
                        model3=tk.Checkbutton(hondamotorozelliksecmeekranı,text="Spacy Alpha",bg="gray",fg="red")
                        model3.place(x=750,y=305)
                        renk1=tk.Checkbutton(hondamotorozelliksecmeekranı,text="Kırmızı",bg="gray",fg="red")
                        renk1.place(x=450,y=455)
                        renk2=tk.Checkbutton(hondamotorozelliksecmeekranı,text="Beyaz",bg="gray",fg="red")
                        renk2.place(x=600,y=455)
                        renk3=tk.Checkbutton(hondamotorozelliksecmeekranı,text="Siyah",bg="gray",fg="red")
                        renk3.place(x=750,y=455)
                        fiyat1=tk.Checkbutton(hondamotorozelliksecmeekranı,text="1000 TL",bg="gray",fg="red")
                        fiyat1.place(x=450,y=605)
                        fiyat2=tk.Checkbutton(hondamotorozelliksecmeekranı,text="2000 TL",bg="gray",fg="red")
                        fiyat2.place(x=600,y=605)
                        fiyat3=tk.Checkbutton(hondamotorozelliksecmeekranı,text="3000 TL",bg="gray",fg="red")
                        fiyat3.place(x=750,y=605)
                        def hondamotorodeme():
                            hondamotorodemeekranı=tk.Tk()
                            hondamotorodemeekranı.state("zoomed")
                            hondamotorodemeekranı.config(bg="gray")
                            hondamotorodemeekranı.title("Honda Motor Ödeme Ekranı")
                            welcome_label=tk.Label(hondamotorodemeekranı,text="Ödeme Yapma Paneline Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                            welcome_label.place(x=400,y=100)
                            yazikartno=tk.Label(hondamotorodemeekranı,text="Kart No : ",font="Verdana 15", bg="red", fg="white",width=17)
                            yazikartno.place(x=230,y=300)
                            yazisonkullanımtarihi=tk.Label(hondamotorodemeekranı,text="Son Kullanım Tarihi : ",font="Verdana 15", bg="red", fg="white")
                            yazisonkullanımtarihi.place(x=230,y=400)
                            yazicvv=tk.Label(hondamotorodemeekranı,text="CVV : ",font="Verdana 15", bg="red", fg="white",width=17)
                            yazicvv.place(x=230,y=500)
                            kartnogirdi=tk.Entry(hondamotorodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            kartnogirdi.place(x=470, y=300, width=900, height=30)
                            sonkullanımtarihigirdi=tk.Entry(hondamotorodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            sonkullanımtarihigirdi.place(x=470, y=400, width=900, height=30)
                            cvvgirdi=tk.Entry(hondamotorodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            cvvgirdi.place(x=470, y=500, width=900, height=30)
                            def ödemehondamotoryazı():
                                yazihondamotorodemetamamlandı=tk.Label(hondamotorodemeekranı,text="ISLEMİNİZ BAŞARIYLA GERÇEKLEŞMİŞTİR.",font="Verdana 15", bg="red", fg="white",width=95,height=2)
                                yazihondamotorodemetamamlandı.place(x=200,y=565)
                            hondamotorodeme=tk.Button(hondamotorodemeekranı,text="Ödemeyi Tamamla",fg="red",bg="black",font="verdana 32",command=ödemehondamotoryazı)
                            hondamotorodeme.place(x=600,y=650)
                        hondamotorodemetamamlabuton=tk.Button(hondamotorozelliksecmeekranı,text="Ödeme Yap",fg="red",bg="black",font="verdana 32",command=hondamotorodeme)
                        hondamotorodemetamamlabuton.place(x=1000,y=440)
                        hondamotorozelliksecmeekranı.mainloop()
                    self.__arac2=tk.Button(motorseçenekleripenceresi,text="Honda",fg="white",bg="black",font="verdana 32",command=hondamotorozellikseçmeişlemiyap)
                    self.__arac2.place(x=400,y=450,width=800)
                    def cavazakiozelliksecmeekranı():
                        cavazakimotorozelliksecmeekranı=tk.Tk()
                        cavazakimotorozelliksecmeekranı.title("Cavazaki Motor Özellikleri Seçme Ekranı")
                        cavazakimotorozelliksecmeekranı.config(bg="gray")
                        cavazakimotorozelliksecmeekranı.state("zoomed")
                        yazicavazakimotorozellik=tk.Label(cavazakimotorozelliksecmeekranı,text="Honda Özellik Seçme Ekranı",font="Verdana 32", bg="red", fg="white")
                        yazicavazakimotorozellik.place(x=475,y=100)
                        yazimodel=tk.Label(cavazakimotorozelliksecmeekranı,text="Model : ",font="Verdana 16", bg="red", fg="white")
                        yazimodel.place(x=300,y=300)
                        yazirenk=tk.Label(cavazakimotorozelliksecmeekranı,text="Renk : ",font="Verdana 16", bg="red",fg="white")
                        yazirenk.place(x=300,y=450)
                        yazifiyat=tk.Label(cavazakimotorozelliksecmeekranı,text="Fiyat : ",font="Verdana 16", bg="red", fg="white")
                        yazifiyat.place(x=300,y=600)
                        model1=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="Kawasaki Z 800",bg="gray",fg="red")
                        model1.place(x=450,y=305)
                        model2=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="Kawasaki EN 500",bg="gray",fg="red")
                        model2.place(x=600,y=305)
                        model3=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="Kawasaki Ninja 250R",bg="gray",fg="red")
                        model3.place(x=750,y=305)
                        renk1=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="Kırmızı",bg="gray",fg="red")
                        renk1.place(x=450,y=455)
                        renk2=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="Beyaz",bg="gray",fg="red")
                        renk2.place(x=600,y=455)
                        renk3=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="Siyah",bg="gray",fg="red")
                        renk3.place(x=750,y=455)
                        fiyat1=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="1000 TL",bg="gray",fg="red")
                        fiyat1.place(x=450,y=605)
                        fiyat2=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="2000 TL",bg="gray",fg="red")
                        fiyat2.place(x=600,y=605)
                        fiyat3=tk.Checkbutton(cavazakimotorozelliksecmeekranı,text="3000 TL",bg="gray",fg="red")
                        fiyat3.place(x=750,y=605)
                        def cavazakiodemeekranı():
                            cavazakimotorodemeekranı=tk.Tk()
                            cavazakimotorodemeekranı.state("zoomed")
                            cavazakimotorodemeekranı.config(bg="gray")
                            cavazakimotorodemeekranı.title("Cavazaki Motor Ödeme Ekranı")
                            welcome_label=tk.Label(cavazakimotorodemeekranı,text="Ödeme Yapma Paneline Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                            welcome_label.place(x=400,y=100)
                            yazikartno=tk.Label(cavazakimotorodemeekranı,text="Kart No : ",font="Verdana 15", bg="red", fg="white",width=17)
                            yazikartno.place(x=230,y=300)
                            yazisonkullanımtarihi=tk.Label(cavazakimotorodemeekranı,text="Son Kullanım Tarihi : ",font="Verdana 15", bg="red", fg="white")
                            yazisonkullanımtarihi.place(x=230,y=400)
                            yazicvv=tk.Label(cavazakimotorodemeekranı,text="CVV : ",font="Verdana 15", bg="red", fg="white",width=17)
                            yazicvv.place(x=230,y=500)
                            kartnogirdi=tk.Entry(cavazakimotorodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            kartnogirdi.place(x=470, y=300, width=900, height=30)
                            sonkullanımtarihigirdi=tk.Entry(cavazakimotorodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            sonkullanımtarihigirdi.place(x=470, y=400, width=900, height=30)
                            cvvgirdi=tk.Entry(cavazakimotorodemeekranı,bg="white", fg="black", font="verdana 17 bold")
                            cvvgirdi.place(x=470, y=500, width=900, height=30)
                            def ödemecavazakimotoryazı():
                                yazicavazakimotorodemetamamlandı=tk.Label(cavazakimotorodemeekranı,text="ISLEMİNİZ BAŞARIYLA GERÇEKLEŞMİŞTİR.",font="Verdana 15", bg="red", fg="white",width=95,height=2)
                                yazicavazakimotorodemetamamlandı.place(x=200,y=565)
                            hondamotorodeme=tk.Button(cavazakimotorodemeekranı,text="Ödemeyi Tamamla",fg="red",bg="black",font="verdana 32",command=ödemecavazakimotoryazı)
                            hondamotorodeme.place(x=600,y=650)
                        cavazakimotorodemetamamlabuton=tk.Button(cavazakimotorozelliksecmeekranı,text="Ödeme Yap",fg="red",bg="black",font="verdana 32",command=cavazakiodemeekranı)
                        cavazakimotorodemetamamlabuton.place(x=1000,y=440)
                        cavazakimotorozelliksecmeekranı.mainloop()
                    self.__arac3=tk.Button(motorseçenekleripenceresi,text="Cavazaki",fg="white",bg="black",font="verdana 32",command=cavazakiozelliksecmeekranı)
                    self.__arac3.place(x=400,y=600,width=800)
                    motorseçenekleripenceresi.mainloop()
            motor=motor("","","")
            def kullanıcıekranı():
                kullanıcıekranı=tk.Tk()
                kullanıcıekranı.title("Kullanıcı ekranı")
                kullanıcıekranı.config(bg="gray")
                kullanıcıekranı.state("zoomed")
                welcomeyazıkullanıcıekranı=tk.Label(kullanıcıekranı,text="Kullanıcı Portalına hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                welcomeyazıkullanıcıekranı.place(x=440,y=150)
                butonaraba=tk.Button(kullanıcıekranı,text="Araba Seçenekleri",fg="white",bg="black",font="verdana 32",command=araba.arabaseçenekleri)
                butonaraba.place(x=300,y=400)
                butonmotor=tk.Button(kullanıcıekranı,text="Motor Seçenekleri",fg="white",bg="black",font="verdana 32",command=motor.motor_seçeneklerimiz)
                butonmotor.place(x=900,y=400)
                kullanıcıekranı.mainloop()
            kullanıcıekranı()    
    butongirişyap=tk.Button(kullanıcıgirispaneli,text="Giriş Yap",fg="white",bg="black",font="verdana 32",command=girişyapkullanıcı)
    butongirişyap.place(x=650,y=580)
    kullanıcıgirispaneli.mainloop()
def satıcıgirişpaneli():
    satıcıgirispaneli=tk.Tk()
    satıcıgirispaneli.state("zoomed")
    satıcıgirispaneli.config(bg="black")
    satıcıgirispaneli.title("Satıcı Giriş Paneli")
    satıcıgirişiwelcomeanaekran=tk.Label(satıcıgirispaneli,text="Satıcı Giriş Paneli",font="Verdana 64", bg="black", fg="red")
    satıcıgirişiwelcomeanaekran.place(x=400,y=100)
    yazikullanıcıadi=tk.Label(satıcıgirispaneli,text="Kullanıcı Adı : ",font="Verdana 15", bg="red", fg="white")
    yazikullanıcıadi.place(x=200,y=300)
    kullaniciadigirdi=tk.Entry(satıcıgirispaneli,bg="gray", fg="black", font="verdana 17 bold")
    kullaniciadigirdi.place(x=380, y=300, width=900, height=30)
    yazisifre=tk.Label(satıcıgirispaneli,text="Sifre : ",font="Verdana 15", bg="red", fg="white")
    yazisifre.place(x=200,y=450,width=150)
    sifregirdi=tk.Entry(satıcıgirispaneli,bg="gray", fg="black",font="verdana 17 bold")
    sifregirdi.place(x=380, y=450, width=900, height=30)
    
    def girişyapsatıcı():
        #We created dict to hold vendor information...
        satıcıbilgileri=dict()
        kullanıcıadı=kullaniciadigirdi.get()
        satıcıbilgileri["kullanıcı adı : "]=kullanıcıadı
        sifre=sifregirdi.get()
        satıcıbilgileri["Şifre : "]=sifre
        print(satıcıbilgileri)
        if satıcıbilgileri["kullanıcı adı : "]==kullanıcıadı and satıcıbilgileri["Şifre : "]==sifre:
            #This class is the parent of the car and motor class.
            class satıcı:
                # This method is created for constructor...
                def __init__(self,marka,model,depo,fiyat,renk):
                    self.__marka=marka
                    self.__model=model
                    self.__depo=depo
                    self.__fiyat=fiyat
                    self.__renk=renk 
            # This class is the engine child class and inherits from the vendor class...
            class motor(satıcı):
                kuruluş="Bu uygulamadaki veriler 2023 verileridir"
                # This method is created for constructor...
                def __init__(self,marka,model,depo,fiyat,renk):
                    super().__init__(marka,model,depo,fiyat,renk)    
                # It is the class method of our motorclass. It takes the cls parameter and is used to return any value in the class...
                @classmethod
                def motoruygulamasıhakkında(cls):
                    motor_paneli=tk.Tk()
                    motor_paneli.state("zoomed")
                    motor_paneli.title("Motorlu Araçlar Paneli")
                    motor_paneli.config(bg="gray")
                    welcome_label=tk.Label(motor_paneli,text="Motorlu Araçlar Paneline Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                    welcome_label.place(x=400,y=100)
                    buton1=tk.Button(motor_paneli,text="Motor Ekle",fg="white",bg="black",font="verdana 32",command=motor.motorbilgileriniekle)
                    buton1.place(x=450,y=300,height=80,width=700)
                    buton1=tk.Button(motor_paneli,text="Motor Bilgilerini Güncelle",fg="white",bg="black",font="verdana 32",command=motor.motorbilgileriniguncelle)
                    buton1.place(x=450,y=500,height=80,width=700)
                    print(cls.kuruluş)
                # This method takes engine information and also this method is a static method because there is no class value in this method.
                @staticmethod
                def motorbilgileriniekle():
                    motoreklepenceresi=tk.Tk()
                    motoreklepenceresi.state("zoomed")
                    motoreklepenceresi.title("Motor Bilgilerini Ekleme Ekranı")
                    motoreklepenceresi.config(bg="gray")
                    açılış_yazısı=tk.Label(motoreklepenceresi,text="Motor Ekleme Portalına Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                    açılış_yazısı.place(x=400,y=100)
                    yazi=tk.Label(motoreklepenceresi,text="Marka : ",font="Verdana 15", bg="red", fg="white")
                    yazi.place(x=230,y=280)
                    yazi_2=tk.Label(motoreklepenceresi,text="Model : ",font="Verdana 15", bg="red", fg="white")
                    yazi_2.place(x=230,y=330)
                    yazi_3=tk.Label(motoreklepenceresi,text="Depo : ",font="Verdana 15", bg="red", fg="white")
                    yazi_3.place(x=230,y=380)
                    yazi_4=tk.Label(motoreklepenceresi,text="Fiyat : ",font="Verdana 15", bg="red", fg="white")
                    yazi_4.place(x=230,y=430)
                    yazi_5=tk.Label(motoreklepenceresi,text="Renk : ",font="Verdana 15", bg="red", fg="white")
                    yazi_5.place(x=230,y=480)
                    marka=tk.Entry(motoreklepenceresi,bg="white", fg="black", font="verdana 17 bold")
                    marka.place(x=330, y=280, width=900, height=30)
                    model=tk.Entry(motoreklepenceresi,bg="white",fg="black",font="verdana 17 bold")
                    model.place(x=330, y=330, width=900, height=30)
                    depo=tk.Entry(motoreklepenceresi,bg="white",fg="black",font="verdana 17 bold")
                    depo.place(x=330, y=380, width=900, height=30)
                    fiyat=tk.Entry(motoreklepenceresi,bg="white",fg="black",font="verdana 17 bold")
                    fiyat.place(x=330, y=430, width=900, height=30)
                    renk=tk.Entry(motoreklepenceresi,bg="white",fg="black",font="verdana 17 bold")
                    renk.place(x=330, y=480, width=900, height=30)
                    def eklemeyazısı():
                        açılış_yazısı=tk.Label(motoreklepenceresi,text="Tüm Bilgiler Veri Tabanına Eklenmiştir...",font="Verdana 32", bg="red", fg="white")
                        açılış_yazısı.place(x=300,y=560)
                    buton1=tk.Button(motoreklepenceresi,text="Oluştur",fg="white",bg="black",font="verdana 32",command=eklemeyazısı)
                    buton1.place(x=650,y=640)
                #This method updates motorcycle information...
                def motorbilgileriniguncelle(self):
                    motor_guncelleme_penceresi=tk.Tk()
                    motor_guncelleme_penceresi.state("zoomed")
                    motor_guncelleme_penceresi.title("Motor Bilgilerini Güncelleme Ekranı")
                    motor_guncelleme_penceresi.config(bg="gray")
                    yazi=tk.Label(motor_guncelleme_penceresi,text="Motor Bilgilerini Güncelleme Portalına Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                    yazi.place(x=250,y=150)
                    self.yazi=tk.Label(motor_guncelleme_penceresi,text="Güncellenecek Bölüm : ",font="Verdana 15", bg="red", fg="white")
                    self.yazi.place(x=130,y=300)
                    key=tk.Entry(motor_guncelleme_penceresi,bg="white", fg="black", font="verdana 17 bold")
                    key.place(x=400, y=300, width=900, height=30)
                    value=tk.Label(motor_guncelleme_penceresi,text="Yeni Değer : ",font="Verdana 15", bg="red", fg="white")
                    value.place(x=130,y=450,width=250)
                    value=tk.Entry(motor_guncelleme_penceresi,bg="white", fg="black", font="verdana 17 bold")
                    value.place(x=400, y=450, width=900, height=30)
                    def eklemeyazısı2():
                        uyarı=tk.Label(motor_guncelleme_penceresi,text="Yeni bilgiler veri tabanına kaydedilmiştir...",font="Verdana 32", bg="red", fg="white")
                        uyarı.place(x=350,y=530)
                    
                    butonduzenle=tk.Button(motor_guncelleme_penceresi,text="Düzenle",fg="white",bg="black",font="verdana 32",command=eklemeyazısı2)
                    butonduzenle.place(x=650,y=630)
            motor=motor("","",100,1000,"")
            # This class is the car class and inherits from the seller class...
            class araba(satıcı):
                def __init__(self, marka, model,depo,fiyat,renk):
                    super().__init__(marka, model,depo,fiyat,renk)
                # This method is coded to create the car add screen...
                def arababilgileriniekle(self):
                    araba_ekle_penceresi=tk.Tk()
                    araba_ekle_penceresi.state("zoomed")
                    araba_ekle_penceresi.title("Araba ekleme ekranı")
                    araba_ekle_penceresi.config(bg="gray")
                    açılış_yazısı=tk.Label(araba_ekle_penceresi,text="Araba Ekleme Portalına Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                    açılış_yazısı.place(x=400,y=100)
                    self.yazi=tk.Label(araba_ekle_penceresi,text="Marka : ",font="Verdana 15", bg="red", fg="white")
                    self.yazi.place(x=230,y=280)
                    self.yazi_2=tk.Label(araba_ekle_penceresi,text="Model : ",font="Verdana 15", bg="red", fg="white")
                    self.yazi_2.place(x=230,y=330)
                    self.yazi_3=tk.Label(araba_ekle_penceresi,text="Depo : ",font="Verdana 15", bg="red", fg="white")
                    self.yazi_3.place(x=230,y=380)
                    self.yazi_4=tk.Label(araba_ekle_penceresi,text="Fiyat : ",font="Verdana 15", bg="red", fg="white")
                    self.yazi_4.place(x=230,y=430)
                    self.yazi_5=tk.Label(araba_ekle_penceresi,text="Renk : ",font="Verdana 15", bg="red", fg="white")
                    self.yazi_5.place(x=230,y=480)
                    self.__marka=tk.Entry(araba_ekle_penceresi,bg="white", fg="black", font="verdana 17 bold")
                    self.__marka.place(x=330, y=280, width=900, height=30)
                    self.__model=tk.Entry(araba_ekle_penceresi,bg="white",fg="black",font="verdana 17 bold")
                    self.__model.place(x=330, y=330, width=900, height=30)
                    self.__depo=tk.Entry(araba_ekle_penceresi,bg="white",fg="black",font="verdana 17 bold")
                    self.__depo.place(x=330, y=380, width=900, height=30)
                    self.__fiyat=tk.Entry(araba_ekle_penceresi,bg="white",fg="black",font="verdana 17 bold")
                    self.__fiyat.place(x=330, y=430, width=900, height=30)
                    self.__renk=tk.Entry(araba_ekle_penceresi,bg="white",fg="black",font="verdana 17 bold")
                    self.__renk.place(x=330, y=480, width=900, height=30)
                    def eklemeyazısı():
                        açılış_yazısı=tk.Label(araba_ekle_penceresi,text="Tüm Bilgiler Veri Tabanına Eklenmiştir...",font="Verdana 32", bg="red", fg="white")
                        açılış_yazısı.place(x=300,y=530)
                    buton1=tk.Button(araba_ekle_penceresi,text="Oluştur",fg="white",bg="black",font="verdana 32",command=eklemeyazısı)
                    buton1.place(x=650,y=600)
                # This method was created to create a car update screen...
                def arababilgileriniguncelle(self):
                    araba_guncelleme_penceresi=tk.Tk()
                    araba_guncelleme_penceresi.state("zoomed")
                    araba_guncelleme_penceresi.title("Araba güncelleme ekranı")
                    araba_guncelleme_penceresi.config(bg="gray")
                    yazihosgeldin=tk.Label(araba_guncelleme_penceresi,text="Araba Guncelleme Portalına Hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                    yazihosgeldin.place(x=350,y=150)
                    guncelenecekdeğer=tk.Label(araba_guncelleme_penceresi,text="Güncellenecek Bölüm : ",font="Verdana 15", bg="red", fg="white")
                    guncelenecekdeğer.place(x=180,y=300)
                    guncelenecekdeğer=tk.Entry(araba_guncelleme_penceresi,bg="white", fg="black", font="verdana 17 bold")
                    guncelenecekdeğer.place(x=450, y=300, width=900, height=30)
                    gunceldeger=tk.Label(araba_guncelleme_penceresi,text="Yeni Değer : ",font="Verdana 15", bg="red", fg="white")
                    gunceldeger.place(x=180,y=450,width=240)
                    gunceldegergiris=tk.Entry(araba_guncelleme_penceresi,bg="white", fg="black", font="verdana 17 bold")
                    gunceldegergiris.place(x=450, y=450, width=900, height=30)
                    def eklemeyazısı2():
                        self.yazi=tk.Label(araba_guncelleme_penceresi,text="Yeni bilgiler veri tabanına kaydedilmiştir...",font="Verdana 32", bg="red", fg="white")
                        self.yazi.place(x=350,y=515)
                    
                    buton1=tk.Button(araba_guncelleme_penceresi,text="Düzenle",fg="white",bg="black",font="verdana 32",command=eklemeyazısı2)
                    buton1.place(x=650,y=600)
            araba=araba("",0,0,0,"kırmızı")
            def araba_işlemleri():
                iç_pencere_araba=tk.Tk()
                iç_pencere_araba.title("Araba İşlemleri")
                iç_pencere_araba.state("zoomed")
                iç_pencere_araba.config(bg="gray")
                yazi=tk.Label(iç_pencere_araba,text="Araba işlemleri Portalına hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                yazi.place(x=400,y=100)
                buton1=tk.Button(iç_pencere_araba,text="Araba Ekle",fg="white",bg="black",font="verdana 32",command=araba.arababilgileriniekle)
                buton1.place(x=650,y=300)
                buton2=tk.Button(iç_pencere_araba,text="Araba Bilgilerini güncelle",fg="white",bg="black",font="verdana 32",command=araba.arababilgileriniguncelle)
                buton2.place(x=500,y=500)
                iç_pencere_araba.mainloop()
            # This method is created for vendor portal...
            def uygulama():
                satıcı_penceresi=tk.Tk()
                satıcı_penceresi.title("Satıcı Portalı")
                satıcı_penceresi.state("zoomed")
                satıcı_penceresi.config(bg="gray")
                yazi=tk.Label(satıcı_penceresi,text="Satıcı Portalına hoşgeldiniz!",font="Verdana 32", bg="red", fg="white")
                yazi.place(x=475,y=200)
                buton1=tk.Button(satıcı_penceresi,text="Araba İşlemleri",fg="white",bg="black",font="verdana 32",command=araba_işlemleri)
                buton1.place(x=250,y=400)
                buton2=tk.Button(satıcı_penceresi,text="Motor İşlemleri",fg="white",bg="black",font="verdana 32",command=motor.motoruygulamasıhakkında)
                buton2.place(x=900,y=400)
                satıcı_penceresi.mainloop()
            uygulama()
    butongirişyap=tk.Button(satıcıgirispaneli,text="Giriş Yap",fg="white",bg="black",font="verdana 32",command=girişyapsatıcı)
    butongirişyap.place(x=650,y=580)
# This class is a parent class inherited from our main screen child class...
class ekran:
    def __init__(self,welcomeanaekran,kullanıcıgirişibuton,satıcıgirişibuton,çıkışbuton,anaekran):
        self.__welcomeanaekran=welcomeanaekran
        self.__kullanıcıgirişibuton=kullanıcıgirişibuton
        self.__satıcıgirişibuton=satıcıgirişibuton
        self.__çıkışbuton=çıkışbuton
        self.__anaekran=anaekran
    
        
# This class inherits from our display parent class...
class anaekran(ekran):
        def __init__(self, welcomeanaekran, kullanıcıgirişibuton, satıcıgirişibuton, çıkışbuton, anaekran):
            super().__init__(welcomeanaekran, kullanıcıgirişibuton, satıcıgirişibuton, çıkışbuton, anaekran)    
        def mainwindow(self):
            self.__anaekran=tk.Tk()
            self.__anaekran.state("zoomed")
            self.__anaekran.config(bg="black")
            self.__anaekran.title("Kirala Götür")
            self.__welcomeanaekran=tk.Label(self.__anaekran,text="Kirala Götür",font="Verdana 64", bg="black", fg="red")
            self.__welcomeanaekran.place(x=530,y=100)
            self.__kullanıcıgirişibuton=tk.Button(self.__anaekran,text="Kullanıcı Girişi",fg="black",bg="gray",font="verdana 32",command=kullanıcıgirispaneli)
            self.__kullanıcıgirişibuton.place(x=450,y=300,height=80,width=700)
            self.__satıcıgirişibuton=tk.Button(self.__anaekran,text="Satıcı Girişi",fg="black",bg="gray",font="verdana 32",command=satıcıgirişpaneli)
            self.__satıcıgirişibuton.place(x=450,y=450,height=80,width=700)
            self.__cikisbuton=tk.Button(self.__anaekran,text="Çıkış Yap",fg="black",bg="gray",font="verdana 32",command=self.__anaekran.destroy)
            self.__cikisbuton.place(x=450,y=600,height=80,width=700)
            self.__anaekran.mainloop()
anaekran=anaekran(0,0,0,0,0)
anaekran.mainwindow()
